@Library('simple-java-maven-app@master') _
pipeline {
    agent any 
    stages {
        stage('Git Checkout') {
            steps {
             gitCheckout(
                branch: "master",
                url: "https://github.com/WadeWilson23/simple-java-maven-app.git"
            )
            }
    }

        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
